### ISSUE TITLE
Event pitches should be integers

### ISSUE THREAD

**Issue by javipus** [accraze/python-twelve-tone#19]
Running
```python
from twelve_tone.composer import Composer
c = Composer()
c.compose()
c.save_to_midi()
```
throws `error: required argument is not an integer`.

This happens because miditime saves pitch info using `struct.pack('>B',event.pitch)`, which requires the second argument to be an integer. Therefore, the problem is fixed by casting numbers in `c.matrix` to `int`.

Environment info:
- OS: elementary OS 0.4.1 Loki
- Python: 3.7.5
- miditime: 1.1.3

**Comment by accraze** [comment]
Thanks for the bug report @javipus! I just confirmed the error happens for me as well on macOS. I will push up a patch shortly. Cheers!
