### ISSUE TITLE
Add CLI args to select tone row or column

### ISSUE THREAD

**Issue by accraze** [accraze/python-twelve-tone#9]
Currently, the `twelve-tone` CLI generates a random melody and takes the top row as it's tone row.
https://github.com/accraze/python-twelve-tone/blob/master/src/twelve_tone/cli.py#L26

There should be some CLI flags that allow you to specify which row or column you wish to use for the generated melody. This should be pretty easy, just update the main to be something like:

```
@click.command()
@click.option('--row', '-r',  default=0, help='Which row should we use?')
@click.option('--col', '-c',  default=None, help='Which column should we use?')
def main(row,column):
    c = Composer()
    c.compose()
    click.echo(c.get_melody(row=row, column=column))
```

**Comment by J0** [comment]
Hi, @accraze can I take this issue?

**Comment by rhythmize** [comment]
Cannot push to repo, returns following error.
`remote: Permission to accraze/python-twelve-tone.git denied to code-player.
fatal: unable to access 'https://github.com/accraze/python-twelve-tone.git/': The requested URL returned error: 403`
